frr version 10.5.1
frr defaults traditional
hostname ecotype2 
!
ip forwarding
!
ip prefix-list multicast permit 224.0.0.0/4
! ip pim ssm default
!
interface eth1
    ip address 10.10.2.2/24
    ip ospf network point-to-point
    ip ospf hello-interval 1
    ip ospf dead-interval 4
    ip ospf area 0
    ip pim
    ip igmp
!
interface eth2
    ip address 10.10.13.1/24
    ip ospf area 0
    ip pim
    ip igmp
!
interface lo
    ip address 10.10.10.3/32
    ip pim
    ip ospf area 0
    ip igmp
!
router ospf 
    router-id 3.3.3.3
    timers throttle spf 10 50 5000
    network 10.10.13.0/24 area 0
    network 10.10.3.0/24 area 0
    network 10.10.10.3/32 area 0
!
router pim
    ssm prefix-list multicast
    bsr candidate-rp priority 103
    bsr candidate-bsr priority 3
    bsr candidate-rp group 224.0.0.0/4
!
line vty
!
