frr version 10.5.1
frr defaults traditional
hostname ecotype1
!
ip forwarding
!
ip prefix-list multicast permit 224.0.0.0/4
! ip pim ssm default
!
interface eth0
    ip address 10.100.1.2/24
!
interface gre1
    tunnel source eth0
    ip address 192.168.1.2/24
    ip ospf network point-to-point
    ip ospf hello-interval 1
    ip ospf dead-interval 4
    ip ospf area 0
    ip pim
    ip igmp
    ip igmp immediate-leave
    ip ospf area 0
!
interface eth1
    ip address 10.10.2.1/24
    ip ospf network point-to-point
    ip ospf hello-interval 1
    ip ospf dead-interval 4
    ip ospf area 0
    ip pim
    ip igmp
    ip igmp immediate-leave
!
interface eth2
    ip address 10.10.12.1/24
    ip ospf area 0
    ip pim
    ip igmp
    ip igmp immediate-leave
!
interface lo
    ip address 10.10.10.2/32
    ip pim
    ip ospf area 0
!
router ospf 
    router-id 2.2.2.2
    timers throttle spf 10 50 5000
    network 192.168.1.0/24 area 0
    network 10.10.2.0/24 area 0
    network 10.10.12.0/24 area 0
    network 10.10.10.2/32 area 0
!
router pim
    ! ssm prefix-list multicast
    bsr candidate-rp priority 102
    bsr candidate-bsr priority 2
    bsr candidate-rp group 224.0.0.0/4
!
line vty
!
