frr version 10.5.1
frr defaults traditional
hostname spirou
!
debug nhrp all
log stdout debugging
nhrp nflog-group 2
nhrp multicast-nflog-group 2
!
ip forwarding
!
ip prefix-list multicast permit 224.0.0.0/4
! ip pim ssm default
!
interface eth0
    ip address 10.100.1.1/24
!
interface gre1
    tunnel source eth0
    ip address 192.168.1.1/32
    ip nhrp map multicast dynamic
    ip nhrp registration no-unique
    ip nhrp network-id 1
    ip ospf area 0
    ip ospf network point-to-multipoint
    ip pim
    ! ip igmp
!
interface eth1
    ip address 10.10.11.1/24
    ip pim
    ip igmp
    ip ospf area 0
!
! interface lo
!     ip address 10.10.10.1/32
!     ip pim
!     ip ospf area 0
!     ip igmp
! !
router ospf 
    router-id 1.1.1.1
    timers throttle spf 10 50 5000
    network 192.168.1.0/24 area 0
    network 10.10.11.0/24 area 0
    redistribute nhrp
!
router pim
    bsr candidate-rp priority 0
    bsr candidate-bsr priority 101
    bsr candidate-rp group 224.0.0.0/4
!
line vty
!
