table ip filter {
        chain INPUT {
                type filter hook input priority filter; policy accept;
        }

        chain FORWARD {
                type filter hook forward priority filter; policy accept;
                oifname "gre1" ip daddr 224.0.0.0/4 log group 2
                oifname "gre1" ip daddr 224.0.0.0/4  drop
        }

        chain OUTPUT {
                type filter hook output priority filter; policy accept;
                oifname "gre1" ip daddr 224.0.0.0/24 log group 2
                oifname "gre1" ip daddr 224.0.0.0/24 drop
        }

}
