topology:
    defaults:
        routers:
            multicast: true
            rp_id: 1
            asm_prefix: "224.0.0.0/4"
            name_prefix: "r"

        links:
            bandwidth: "30Mbit"
            loss: "0%"
            burst: "0%"
            delay: "0ms"
            buffer: 100000
            multicast: true

    routers:
        num: 7
        # overrides:
        #   r2:
        #     multicast: false
        links:
            - endpoints: ["r1", "r2"]
            - endpoints: ["r1", "r3"]
            - endpoints: ["r1", "r5"] 
            - endpoints: ["r2", "r4"]
            - endpoints: ["r3", "r4"]
            - endpoints: ["r3", "r7"]
            - endpoints: ["r3", "r5"]
            - endpoints: ["r5", "r6"]
            - endpoints: ["r6", "r7"]
            - endpoints: ["r7", "r4"]

    servers: ["server1"]
    clients:
        num: 4

    links:
        - endpoints: ["r1", "server1"] 
        - endpoints: ["r5", "client1"]
        - endpoints: ["r6", "client2"]
        - endpoints: ["r7", "client3"]
        - endpoints: ["r4", "client4"]
