topology:
    defaults:
        routers:
            multicast: True
            rp_id: 1
            use_asm: false
            asm_prefix: "224.0.0.0/4"

        links:
            bandwidth: "100Mbit"
            loss: "0%"
            burst: "0%"
            delay: "0ms"
            buffer: 10000000
            multicast: True

    routers:
        num: 2
        links:
            - endpoints: ["r1", "r2"]
              multicast: false
              gre: true

    servers: ["server1"]
    clients:
        num: 2

    links:
        - endpoints: ["r1", "server1"]
        - endpoints: ["r2", "client1"]
        - endpoints: ["r2", "client2"]
