topology:
    defaults:
        routers:
            multicast: true
            rp_id: 1
            asm_prefix: "224.0.0.0/4"
            name_prefix: "r"
            use_asm: false

        links:
            bandwidth: "100Mbit"
            loss: "0.01%"
            burst: "15%"
            delay: "1ms"
            buffer: 100000
            multicast: true

    routers:
        num: 3
        links:
            - endpoints: ["r1", "r2"]
            - endpoints: ["r1", "r3"]

    servers: ["server1"]
    clients:
        num: 35

    # RECEIVERS={3, 5, 7, 9, 11, 13, 15, 17, 19, 21, 23, 25}
    # The test will start with only 3 receivers used (client 1 is always included), then add 2 clients for each test
    links:
        - endpoints: ["r1", "server1"]

        # Client 1 is the sender
        - endpoints: ["r1", "client1"]

        - endpoints: ["r2", "client2"]
        - endpoints: ["r3", "client3"]

        - endpoints: ["r2", "client4"]
        - endpoints: ["r3", "client5"]

        - endpoints: ["r2", "client6"]
        - endpoints: ["r3", "client7"]

        - endpoints: ["r2", "client8"]
        - endpoints: ["r3", "client9"]

        - endpoints: ["r2", "client10"]
        - endpoints: ["r3", "client11"]

        - endpoints: ["r2", "client12"]
        - endpoints: ["r3", "client13"]

        - endpoints: ["r2", "client14"]
        - endpoints: ["r3", "client15"]

        - endpoints: ["r2", "client16"]
        - endpoints: ["r3", "client17"]

        - endpoints: ["r2", "client18"]
        - endpoints: ["r3", "client19"]

        - endpoints: ["r2", "client20"]
        - endpoints: ["r3", "client21"]

        - endpoints: ["r2", "client22"]
        - endpoints: ["r3", "client23"]

        - endpoints: ["r2", "client24"]
        - endpoints: ["r3", "client25"]

        - endpoints: ["r2", "client26"]
        - endpoints: ["r3", "client27"]

        - endpoints: ["r2", "client28"]
        - endpoints: ["r3", "client29"]

        - endpoints: ["r2", "client30"]
        - endpoints: ["r3", "client31"]

        - endpoints: ["r2", "client32"]
        - endpoints: ["r3", "client33"]

        - endpoints: ["r2", "client34"]
        - endpoints: ["r3", "client35"]
