topology:
    defaults:
        routers:
            multicast: true
            rp_id: 1
            asm_prefix: "224.0.0.0/4"
            name_prefix: "r"
            use_asm: false

        links:
            bandwidth: "10Gbit"
            loss: "0%"
            burst: "0%"
            delay: "1ms"
            buffer: 100000000
            multicast: true

    routers:
        num: 1

    servers: ["server1"]
    clients:
        # num: 25
        # num: 35
        # num: 55
        # num: 75
        num: 101

        # RECEIVERS={3, 5, 7, 9, 11, 13, 15, 17, 19, 21, 23, 25}
        # The test will start with only 3 receivers used (client 1 is always included), then add 2 clients for each test
    links:
        - endpoints: ["r1", "server1"]

        # Client 1 is the sender
        - endpoints: ["r1", "client1"]

        - endpoints: ["r1", "client2"]
        - endpoints: ["r1", "client3"]
        - endpoints: ["r1", "client4"]
        - endpoints: ["r1", "client5"]
        - endpoints: ["r1", "client6"]
        - endpoints: ["r1", "client7"]
        - endpoints: ["r1", "client8"]
        - endpoints: ["r1", "client9"]
        - endpoints: ["r1", "client10"]
        - endpoints: ["r1", "client11"]
        - endpoints: ["r1", "client12"]
        - endpoints: ["r1", "client13"]
        - endpoints: ["r1", "client14"]
        - endpoints: ["r1", "client15"]
        - endpoints: ["r1", "client16"]
        - endpoints: ["r1", "client17"]
        - endpoints: ["r1", "client18"]
        - endpoints: ["r1", "client19"]
        - endpoints: ["r1", "client20"]
        - endpoints: ["r1", "client21"]
        - endpoints: ["r1", "client22"]
        - endpoints: ["r1", "client23"]
        - endpoints: ["r1", "client24"]
        - endpoints: ["r1", "client25"]
        - endpoints: ["r1", "client26"]
        - endpoints: ["r1", "client27"]
        - endpoints: ["r1", "client28"]
        - endpoints: ["r1", "client29"]
        - endpoints: ["r1", "client30"]
        - endpoints: ["r1", "client31"]
        - endpoints: ["r1", "client32"]
        - endpoints: ["r1", "client33"]
        - endpoints: ["r1", "client34"]
        - endpoints: ["r1", "client35"]
        - endpoints: ["r1", "client36"]
        - endpoints: ["r1", "client37"]
        - endpoints: ["r1", "client38"]
        - endpoints: ["r1", "client39"]
        - endpoints: ["r1", "client40"]
        - endpoints: ["r1", "client41"]
        - endpoints: ["r1", "client42"]
        - endpoints: ["r1", "client43"]
        - endpoints: ["r1", "client44"]
        - endpoints: ["r1", "client45"]
        - endpoints: ["r1", "client46"]
        - endpoints: ["r1", "client47"]
        - endpoints: ["r1", "client48"]
        - endpoints: ["r1", "client49"]
        - endpoints: ["r1", "client50"]
        - endpoints: ["r1", "client51"]
        - endpoints: ["r1", "client52"]
        - endpoints: ["r1", "client53"]
        - endpoints: ["r1", "client54"]
        - endpoints: ["r1", "client55"]
        - endpoints: ["r1", "client56"]
        - endpoints: ["r1", "client57"]
        - endpoints: ["r1", "client58"]
        - endpoints: ["r1", "client59"]
        - endpoints: ["r1", "client60"]
        - endpoints: ["r1", "client61"]
        - endpoints: ["r1", "client62"]
        - endpoints: ["r1", "client63"]
        - endpoints: ["r1", "client64"]
        - endpoints: ["r1", "client65"]
        - endpoints: ["r1", "client66"]
        - endpoints: ["r1", "client67"]
        - endpoints: ["r1", "client68"]
        - endpoints: ["r1", "client69"]
        - endpoints: ["r1", "client70"]
        - endpoints: ["r1", "client71"]
        - endpoints: ["r1", "client72"]
        - endpoints: ["r1", "client73"]
        - endpoints: ["r1", "client74"]
        - endpoints: ["r1", "client75"]
        - endpoints: ["r1", "client76"]
        - endpoints: ["r1", "client77"]
        - endpoints: ["r1", "client78"]
        - endpoints: ["r1", "client79"]
        - endpoints: ["r1", "client80"]
        - endpoints: ["r1", "client81"]
        - endpoints: ["r1", "client82"]
        - endpoints: ["r1", "client83"]
        - endpoints: ["r1", "client84"]
        - endpoints: ["r1", "client85"]
        - endpoints: ["r1", "client86"]
        - endpoints: ["r1", "client87"]
        - endpoints: ["r1", "client88"]
        - endpoints: ["r1", "client89"]
        - endpoints: ["r1", "client90"]
        - endpoints: ["r1", "client91"]
        - endpoints: ["r1", "client92"]
        - endpoints: ["r1", "client93"]
        - endpoints: ["r1", "client94"]
        - endpoints: ["r1", "client95"]
        - endpoints: ["r1", "client96"]
        - endpoints: ["r1", "client97"]
        - endpoints: ["r1", "client98"]
        - endpoints: ["r1", "client99"]
        - endpoints: ["r1", "client100"]
        - endpoints: ["r1", "client101"]
