ip forwarding
ip prefix-list multicast permit 224.0.0.0/4
router pim
  ssm prefix-list multicast
exit
router isis 1
  is-type level-1
  redistribute connected
  net 49.0000.0000.0000.0002.00
  lsp-timers level-1 gen-interval 5 refresh-interval 10 max-lifetime 1200
  spf-interval 5
exit

interface lo
  ip pim
  ip igmp
  ip igmp immediate-leave
  ip router isis 1
  isis network point-to-point
  isis metric 1
  isis passive
  ip address 10.255.1.1/32
exit
interface r1-r2-gre
  ip pim
  ip igmp
  ip igmp immediate-leave
  ip router isis 1
  isis network point-to-point
  isis metric 1
  ip address 10.50.1.0/24
exit
interface r1-server1
  ip pim
  ip igmp
  ip igmp immediate-leave
  ip router isis 1
  isis network point-to-point
  isis metric 1
  isis passive
  ip address 10.10.0.0/24
exit
