topology:
    defaults:
        routers:
            multicast: true
            rp_id: 2
            asm_prefix: "224.0.0.0/4"
            name_prefix: "r"
            use_asm: false

        links:
            bandwidth: "100Mbit"
            loss: "0%"
            burst: "0%"
            delay: "1ms"
            buffer: 100000
            multicast: true

    routers:
        num: 5
        links:
            - endpoints: ["r1", "r2"]
            - endpoints: ["r2", "r3"]
            - endpoints: ["r2", "r4"]
            - endpoints: ["r2", "r5"]
            # - endpoints: ["r3", "r4"]
            - endpoints: ["r4", "r5"]
            - endpoints: ["r3", "r5"]

    servers: ["server1"]
    clients:
        num: 11

    # RECEIVERS={3, 5, 7, 9, 11}
    # The test will start with only 3 receivers used (client 1 is always included)
    links:
        - endpoints: ["r1", "server1"]

        # Client 1 is the sender
        - endpoints: ["r2", "client1"]

        - endpoints: ["r3", "client2"]
        - endpoints: ["r4", "client3"]

        - endpoints: ["r5", "client4"]
        - endpoints: ["r5", "client5"]

        - endpoints: ["r3", "client6"]
        - endpoints: ["r4", "client7"]

        - endpoints: ["r2", "client8"]
        - endpoints: ["r5", "client9"]

        - endpoints: ["r3", "client10"]
        - endpoints: ["r4", "client11"]
